name: Build Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  package-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile Archival Payload
        working-directory: ./absolute-rtl
        run: |
          zip -r ../AbsoluteRTL-Chromium.zip . -x "*.git*" "*.github*" "README.md" "LICENSE" ".gitignore"
          cp ../AbsoluteRTL-Chromium.zip ../AbsoluteRTL-Firefox.xpi

      - name: Attach Assets to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} AbsoluteRTL-Chromium.zip AbsoluteRTL-Firefox.xpi
